project:
  type: book
  output-dir: _book

book:
  title: "Manual de Usuario - Bot SSAB Chile"
  author: "Luis Aguilera A."
  date: "2025-11-06"
  
  navbar:
    background: "#002F6C"
    logo: assets/ssab-logo.svg
    title: false
    search: true
  
  chapters:
    - index.qmd
    - intro.qmd
    - requisitos.qmd
    - inicio.qmd
    - clientes.qmd
    - fichas.qmd
    - cuentas.qmd
    - info-ssab.qmd
    - casos-uso.qmd
    - faq.qmd
    - downloads.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: false
    code-block-bg: true
    code-block-border-left: "#0d6efd"
